### ISSUE TITLE
SyntaxError: f-string: unmatched '['

### ISSUE THREAD

**Issue by mholder96** [vincentl/linea#1]
I get this error when I try to run linea.py: 

C:\Users\M\Documents\Linea\linea-main\src>python linea.py
  File "C:\Users\M\Documents\Linea\linea-main\src\linea.py", line 143
    print(f'Region: http://bboxfinder.com/#{region['south']},{region['west']},{region['north']},{region['east']}')
                                                                              ^^^^^
SyntaxError: f-string: unmatched '['

I'm running Windows 10, python 3.10.8

**Comment by vincentl** [comment]
Please run 

```bash
python --version
```

and include the output in a comment

**Comment by mholder96** [comment]
Here is my version:
C:\Users\M\Documents\Linea\linea-main\src>python --version
Python 3.10.8

But it looks like I may have fixed that by replacing all the inner apostrophes in the print statement with double apostrophes like so:
print(f'Region: http://bboxfinder.com/#{region["south"]},{region["west"]},{region["north"]},{region["east"]}')

However, now I get a different error: 
C:\Users\M\Documents\Linea\linea-main\src>python linea.py
Traceback (most recent call last):
  File "C:\Users\M\Documents\Linea\linea-main\src\linea.py", line 18, in <module>
    from contour import contours
  File "C:\Users\M\Documents\Linea\linea-main\src\contour.py", line 42
    if z[*pixel] != z[*check]:
         ^
SyntaxError: invalid syntax

**Comment by mholder96** [comment]
Oops, just realized I'm not actually running it with a YAML config file yet, so that might be the cause of this second error. I will try again and update you

**Comment by mholder96** [comment]
Hmm, still getting that error: 

C:\Users\M\Documents\Linea>python linea-main/src/linea.py Yosemite/yosemite.yaml
Traceback (most recent call last):
  File "C:\Users\M\Documents\Linea\linea-main\src\linea.py", line 18, in <module>
    from contour import contours
  File "C:\Users\M\Documents\Linea\linea-main\src\contour.py", line 42
    if z[*pixel] != z[*check]:
         ^
SyntaxError: invalid syntax

I did put my api key in the yosemite example yaml as well

**Comment by mholder96** [comment]
Okay, so I updated my python to latest version 3.12.5, and I tried the same example. I got further, but then hit this error:

C:\Users\M\Documents\Linea>python linea-main/src/linea.py Yosemite/yosemite.yaml
Region: http://bboxfinder.com/#37.705105,-119.664105,37.769248,-119.519888
Downloading data...
Using 90.293380 real-meters/scale-mm for xy
  38.346457 real-meters/layer-mm for z
  12 layers
Data grid has shape (518, 230)
Traceback (most recent call last):
  File "C:\Users\M\Documents\Linea\linea-main\src\linea.py", line 209, in <module>
    svg.Rect(
    ^^^^^^^^
AttributeError: module 'svg' has no attribute 'Rect'

**Comment by vincentl** [comment]
I developed with Python 3.12.4. So that at least explains the f-string error. Python improved f-string handling [PEP 701](https://docs.python.org/3/whatsnew/3.12.html#whatsnew312-pep701).

I just check Python 3.11.9 works with only the f-string change.

Are you able to upgrade your python3?

**Comment by mholder96** [comment]
Good news, I got it to work 😄 I noticed the comment in your setup instructions top reinstall svg.py if I get that error and followed that and it worked.

It looks like python 3.10 is not compatible with your program. You should update that in your instructions.

Thanks for your help! Looking forward to trying out your program, it looks really cool :) have a great day!

**Comment by vincentl** [comment]
Thanks for report this. I just pushed commit 6930e9b81ec1c21c4034377412abdae109ba10b1 to check for at least 3.12
